name: Scheduled API Request

on:
  schedule:
    # This runs every 15 minutes (Cron syntax)
    - cron: "*/15 * * * *"
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  send-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          KOKO_USERNAME: ${{ secrets.KOKO_USERNAME }}
          KOKO_PASSWORD: ${{ secrets.KOKO_PASSWORD }}
          MINT_USERNAME: ${{ secrets.MINTPAY_USERNAME }}
          MINT_PASSWORD: ${{ secrets.MINTPAY_PASSWORD }}
          DATA_SUBMIT_ENDPOIT: ${{ secrets.DATA_SUBMIT_ENDPOIT }}
        run: node scrape.js
